apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
data:
  tergum.yml: {{ required ".Values.tergumConfig is required" .Values.tergumConfig | toJson | quote }}
