apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.rootProject.name }}
  namespace: {{ .Release.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: 
  # Allow project to deploy anywhere
  destinations:
    - namespace: "*"
      server: "*"

  sourceRepos: 
  {{- range .Values.rootProject.sourceRepos }}
    - {{. |quote }}
  {{- end }}

