apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.rootApp.name}}
  namespace: {{ .Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.rootProject.name}}
  source:
    path: {{ .Values.rootApp.source.path }}
    repoURL: {{ .Values.rootApp.source.repoURL }}
    targetRevision: HEAD